{% set name = "loopstructuralvisualisation" %}

package:
  name: "{{ name|lower }}"
  version: "{{ environ.get('GIT_DESCRIBE_TAG', '') }}"

source:
  git_url: https://github.com/Loop3D/loopstructural-visualisation

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - python
  run:
    - LoopStructural
    - pyvista




about:
  home: "https://github.com/Loop3D/LoopStructural"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Implicit 3D geological modelling library"
  doc_url: "https://loop3d.github.io/LoopStructural/"
  dev_url: 

extra:
  recipe-maintainers:
    - lachlangrose