{% set name = "loopstructuralvisualisation" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    git_url: https://github.com/Loop3D/loopstructural-visualisation


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy >=1.18
    - pyvista >=0.42
    - loopstructural

test:
  imports:
    - loopstructuralvisualisation
  commands:
    - pip check
  requires:
    - pip

about:
  summary: 3D geological modelling
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lachlangrose
